project_id = "bptdeuhuhfuczmvasqpn"

[functions.admin-validate]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.get-driver-details]
verify_jwt = false

[functions.get-manager-details]
verify_jwt = false
