
-- Make driver-documents bucket private
UPDATE storage.buckets SET public = false WHERE id = 'driver-documents';

-- Create storage policies for driver-documents (private access)
-- Allow authenticated users to upload to their own folder
CREATE POLICY "Drivers can upload own documents"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'driver-documents');

-- Allow reading own documents (via signed URLs generated by edge function)
CREATE POLICY "Service role can read all documents"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'driver-documents');

-- Allow deleting own documents
CREATE POLICY "Users can delete own documents"
ON storage.objects FOR DELETE
TO anon, authenticated
USING (bucket_id = 'driver-documents');
